# FROM adoptopenjdk/openjdk11:alpine-jre


# ARG JAR_FILE=target/user-0.0.1-SNAPSHOT.jar


# WORKDIR /app


# COPY ${JAR_FILE} app.jar


# ENTRYPOINT ["java","-jar","app.jar"]

FROM maven:3.5-jdk-11
COPY . /app